### DISCUSSION TITLE
Add issue link to PR [workflow]

### DISCUSSION THREAD

**Discussion by mepox** [trebol-ecommerce/trebol-backend-monolith#188] [Ideas]
Hi @bglamadrid !

I explored github actions lately and I found two useful actions/workflow what I also use in my personal project so I thought I share in case you are interested.

This one adds an issue link to a newly opened PR. It appends the PR description and adds a link to the issue (to the bottom by default). This also visible in the original issue because the issue was referenced in the PR so it's clear that the two are connected. There is one requirement that the PR branch has to be prefixed, by default with "issue-" and the issue number.

Source: https://github.com/tkt-actions/add-issue-links

My workflow file as an example:
```
# Auto links PR to an issue
# Branch must be prefixed with 'issue-' and the issue number. For example 'issue-123'

name: 'Issue Links'
on:
  pull_request:
    types: [opened]

jobs:
  issue-links:
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.8.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}' # required
          branch-prefix: 'issue-' # required
```
