### DISCUSSION TITLE
Close related issue [workflow]

### DISCUSSION THREAD

**Discussion by mepox** [trebol-ecommerce/trebol-backend-monolith#189] [Ideas]
Hi @bglamadrid !

This is the second github action I wanted to share. This is independent of the other one I mentioned.

So this one close the related issue when you merge a PR. The requirement is to use a prefix in the PR title like: `Close #1` etc.

Source: https://github.com/ldez/gha-mjolnir

Example:
```
# Close issues related to a merged pull request based on main branch.

name: Close issues

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
